using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;

namespace NHibernateCacheTest
{
	/// <summary>
	/// 
	/// Generated by CodeSmith Generator
	/// </summary>
	[DataContract]
	public class KCDJJZD
    {
        
		#region Data Members
		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = true)]
		public virtual int BSM { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = true)]
		public virtual int DKBSM { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual string DKBH { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual string QH { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual string JZDH { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual decimal XZB { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual decimal YZB { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual decimal WKID { get; set; }
		#endregion
	}
}

