using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;

namespace IocCoreTest.IocPlugin.Helper
{
	/// <summary>
	/// 
	/// Generated by CodeSmith Generator
	/// </summary>
	[DataContract]
	public class CITY
    {
        
		#region Data Members
		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = true)]
		public virtual int SID { get; set; }
		
		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual string NAME { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
		public virtual int PROVINCEID { get; set; }
        
        /// <summary>
        /// 
        /// </summary>
        [DataMember(IsRequired = false)]
        public virtual int COUNTRYID { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
        public virtual decimal LONGITUDE { get; set; }

		/// <summary>
        /// 
        /// </summary>
		[DataMember(IsRequired = false)]
        public virtual decimal LATITUDE { get; set; }

		#endregion
	}
}

